version: '3.4'

services:
  skoruba.duende.identityserver.admin:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    labels:
      com.microsoft.visualstudio.debuggee.arguments: ' --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "bin/Debug/net5.0/Skoruba.Duende.IdentityServer.Admin.dll" /seed'

  skoruba.duende.identityserver.admin.api:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  skoruba.duende.identityserver.sts.identity:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
