version: '3.4'

services:
  skorubaduende.identityserveradmin.admin:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    labels:
      com.microsoft.visualstudio.debuggee.arguments: ' --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "bin/Debug/net6.0/SkorubaDuende.IdentityServerAdmin.Admin.dll" /seed'

  skorubaduende.identityserveradmin.admin.api:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  skorubaduende.identityserveradmin.sts.identity:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
